//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoHints {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HintResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HintResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DemoHints.HintResources", typeof(HintResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not have an attribute with its language specified.
        /// </summary>
        internal static string RDAnalyzerAttributeMessageFormat {
            get {
                return ResourceManager.GetString("RDAnalyzerAttributeMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzer doesn&apos;t have the DiagnosticAnalyzer Attribute.
        /// </summary>
        internal static string RDAnalyzerAttributeTitle {
            get {
                return ResourceManager.GetString("RDAnalyzerAttributeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not have a Descriptor with name _descriptor.
        /// </summary>
        internal static string RDAnalyzerDescriptorMessageFormat {
            get {
                return ResourceManager.GetString("RDAnalyzerDescriptorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzer does not have a Descriptor set up.
        /// </summary>
        internal static string RDAnalyzerDescriptorTitle {
            get {
                return ResourceManager.GetString("RDAnalyzerDescriptorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzer must inherit from DiagnosticAnalyzer.
        /// </summary>
        internal static string RDAnalyzerInheritDescription {
            get {
                return ResourceManager.GetString("RDAnalyzerInheritDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not inherit from DiagnosticAnalyzer.
        /// </summary>
        internal static string RDAnalyzerInheritMessageFormat {
            get {
                return ResourceManager.GetString("RDAnalyzerInheritMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzer not inheriting from correct class.
        /// </summary>
        internal static string RDAnalyzerInheritTitle {
            get {
                return ResourceManager.GetString("RDAnalyzerInheritTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not correctly initialized.
        /// </summary>
        internal static string RDAnalyzerInitializeMessageFormat {
            get {
                return ResourceManager.GetString("RDAnalyzerInitializeMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correctly Initialize the analyzer.
        /// </summary>
        internal static string RDAnalyzerInitializeTitle {
            get {
                return ResourceManager.GetString("RDAnalyzerInitializeTitle", resourceCulture);
            }
        }
    }
}
